version: "3.9"
services:
  db:
    container_name: database_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
    expose:
      - 5432
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
  api:
    restart: always
    build:
      context: ./back/HR-portal-api
    ports:
      - "20421:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      "ConnectionStrings:DB": "Server=${DB_HOST}; Port=${DB_PORT}; Database=${DB_DATABASE}; User ID=${DB_USERNAME}; Password=${DB_PASSWORD}; Pooling=true"
      "JwtAuth:SecretKey": "${JWT_SECRET}"
  front:
    restart: always
    build:
      context: ./front
    ports:
      - "80:4200"
    depends_on:
      - api


volumes:
  db:
    driver: local